/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package threadrelay;

/**
 *
 * @author braccalenti.leonardo
 */
public class Grafica extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Grafica.class.getName());

    /**
     * Creates new form Grafica
     */
    public Grafica() {
        initComponents();
        setTitle("Staffetta");
        setSize(400, 400);

        btn_avvia.addActionListener(e -> avvia());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_avvia = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btn_avvia.setText("AVVIA");
        btn_avvia.addActionListener(this::btn_avviaActionPerformed);
        getContentPane().add(btn_avvia);
        btn_avvia.setBounds(180, 260, 72, 23);

        lbl1.setText("0");
        getContentPane().add(lbl1);
        lbl1.setBounds(210, 30, 20, 16);

        lbl2.setText("0");
        getContentPane().add(lbl2);
        lbl2.setBounds(210, 60, 20, 16);

        lbl3.setText("0");
        getContentPane().add(lbl3);
        lbl3.setBounds(210, 90, 20, 16);

        lbl4.setText("0");
        getContentPane().add(lbl4);
        lbl4.setBounds(210, 120, 20, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_avviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_avviaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_avviaActionPerformed

    void avvia(){
        Staffetta.Corridore observer = (n, valore) -> {
        // TUTTO lo switch deve stare dentro invokeLater
        java.awt.EventQueue.invokeLater(() -> {
            switch (n) {
                case 1 -> lbl1.setText(String.valueOf(valore));
                case 2 -> lbl2.setText(String.valueOf(valore));
                case 3 -> lbl3.setText(String.valueOf(valore));
                case 4 -> lbl4.setText(String.valueOf(valore));
            }
        });
    };

        Staffetta t1 = new Staffetta(1);
        Staffetta t2 = new Staffetta(2);
        Staffetta t3 = new Staffetta(3);
        Staffetta t4 = new Staffetta(4);

        t1.sblocca();
        
        t1.setPrecedente(t2);
        t2.setPrecedente(t3);
        t3.setPrecedente(t4);
        
        t1.addCorridore(observer);
        t2.addCorridore(observer);
        t3.addCorridore(observer);
        t4.addCorridore(observer);
        
        t1.start();
        t2.start();
        t3.start();
        t4.start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Grafica().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_avvia;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    // End of variables declaration//GEN-END:variables
}
